# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Roman\Desktop\PythonStuff\HashtagResearch\GUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(451, 474)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 291, 31))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.hashtagText = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.hashtagText.setObjectName("hashtagText")
        self.gridLayout.addWidget(self.hashtagText, 0, 0, 1, 1)
        self.hashtagSearch = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.hashtagSearch.setObjectName("hashtagSearch")
        self.gridLayout.addWidget(self.hashtagSearch, 0, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 221, 401))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listLow = QtWidgets.QListWidget(self.gridLayoutWidget_2)
        self.listLow.setObjectName("listLow")
        self.gridLayout_2.addWidget(self.listLow, 1, 0, 1, 1)
        self.labelLow = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.labelLow.setObjectName("labelLow")
        self.gridLayout_2.addWidget(self.labelLow, 0, 0, 1, 1)
        self.labelMed = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.labelMed.setObjectName("labelMed")
        self.gridLayout_2.addWidget(self.labelMed, 5, 0, 1, 1)
        self.labelHigh = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.labelHigh.setObjectName("labelHigh")
        self.gridLayout_2.addWidget(self.labelHigh, 7, 0, 1, 1)
        self.listHigh = QtWidgets.QListWidget(self.gridLayoutWidget_2)
        self.listHigh.setObjectName("listHigh")
        self.gridLayout_2.addWidget(self.listHigh, 8, 0, 1, 1)
        self.listMed = QtWidgets.QListWidget(self.gridLayoutWidget_2)
        self.listMed.setObjectName("listMed")
        self.gridLayout_2.addWidget(self.listMed, 6, 0, 1, 1)
        self.plainTextTags = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextTags.setGeometry(QtCore.QRect(240, 180, 201, 271))
        self.plainTextTags.setObjectName("plainTextTags")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(240, 50, 201, 121))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.browserOpen = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.browserOpen.setObjectName("browserOpen")
        self.gridLayout_3.addWidget(self.browserOpen, 3, 0, 1, 2)
        self.tagLblCmp = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.tagLblCmp.setText("")
        self.tagLblCmp.setObjectName("tagLblCmp")
        self.gridLayout_3.addWidget(self.tagLblCmp, 2, 1, 1, 1)
        self.tagCompetitionLevel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.tagCompetitionLevel.setObjectName("tagCompetitionLevel")
        self.gridLayout_3.addWidget(self.tagCompetitionLevel, 2, 0, 1, 1)
        self.tagNameLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.tagNameLabel.setObjectName("tagNameLabel")
        self.gridLayout_3.addWidget(self.tagNameLabel, 0, 0, 1, 1)
        self.tagLblNum = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.tagLblNum.setText("")
        self.tagLblNum.setObjectName("tagLblNum")
        self.gridLayout_3.addWidget(self.tagLblNum, 1, 1, 1, 1)
        self.tagLbl = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.tagLbl.setText("")
        self.tagLbl.setObjectName("tagLbl")
        self.gridLayout_3.addWidget(self.tagLbl, 0, 1, 1, 1)
        self.tagNumberLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.tagNumberLabel.setObjectName("tagNumberLabel")
        self.gridLayout_3.addWidget(self.tagNumberLabel, 1, 0, 1, 1)
        self.addButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.addButton.setObjectName("addButton")
        self.gridLayout_3.addWidget(self.addButton, 4, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TagBuddy"))
        self.hashtagSearch.setText(_translate("MainWindow", "Search Hashtag"))
        self.labelLow.setText(_translate("MainWindow", "Low Competition"))
        self.labelMed.setText(_translate("MainWindow", "Medium Competition"))
        self.labelHigh.setText(_translate("MainWindow", "High Competition"))
        self.browserOpen.setText(_translate("MainWindow", "Navigate To Tag Page"))
        self.tagCompetitionLevel.setText(_translate("MainWindow", "Tag Competition:"))
        self.tagNameLabel.setText(_translate("MainWindow", "Selected Tag:"))
        self.tagNumberLabel.setText(_translate("MainWindow", "Tag Count:"))
        self.addButton.setText(_translate("MainWindow", "Add"))
